/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    PageLayout: typeof import('./../src/components/layout/pageLayout.vue')['default']
  }
}
